Community_Medicine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Community_Medicine.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Community_Medicine/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Community_Medicine.Data;
using Community_Medicine.Models;

namespace Community_Medicine.Controllers
{

    public class MedicineController : Controller
    {

        private MedicineGateway mGate = new MedicineGateway();
        private CenterGateway cGate = new CenterGateway();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, Dose")] Medicine m) {

            if (ModelState.IsValid)
            {
                if (mGate.Save(m))
                    return RedirectToAction("index", "Home");
                return View(m);
            }
            
            return View(m);
        }


        [HttpPost]
        public ActionResult SendMedicine([Bind(Include = "CenterId, MedicineId, Qty")] CenterMedicineLinker cml)
        {

            ViewBag.CenterId = new SelectList(cGate.GetAll(), "Id", "Name");
            ViewBag.MedicineId = new SelectList(mGate.GetAll(), "Id", "Name");

            if (ModelState.IsValid)
            {
                if (cGate.SaveCenterMedicineLinker(cml))
                {
                    ViewBag.Message = "Successful";
                    //return RedirectToAction("index", "Home");
                    return View();
                }

                return View();
            }

            return View();
        }


        [HttpGet]
        public ActionResult SendMedicine()
        {
            //ViewBag.CenterId = new SelectList(cGate.GetAll(), "Id", "Name");
            //ViewBag.MedicineId = new SelectList(mGate.GetAll(), "Id", "Name");
            return View();
        }

        public JsonResult GetAllMeds() {
            var allmeds = mGate.GetAll();

            return Json(allmeds, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SendMeds(int centerid, int medid, int qty)
        {
            CenterMedicineLinker cml = new CenterMedicineLinker()
            {
                CenterId = centerid,
                MedicineId = medid,
                Qty = qty
            };

            if (cGate.SaveCenterMedicineLinker(cml)) {
                
                
                return Json(true, JsonRequestBehavior.AllowGet);

            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

	}
}

Community_Medicine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Community_Medicine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Community_Medicine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Community Medicine</h1>
    @*<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Send medicine to a center</h2>
        @*<p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
        <div class="btn btn-default">
            @Html.ActionLink("Send", "SendMedicine", "Medicine")
        </div>
    </div>
    <div class="col-md-4">
        <h2>Create a new Center</h2>
        @*<p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>*@
        <div class="btn btn-default">
            @Html.ActionLink("Create", "Create", "Center")
        </div>
    </div>
    
    <div class="col-md-4">
        @*<h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>*@
    </div>
</div>